AMAZON_FREERTOS_ABSTRACTIONS_DIR := ../../../../../../../../libraries/abstractions

COMPONENT_SRCDIRS := .
COMPONENT_ADD_INCLUDEDIRS := include

ifdef CONFIG_TCPIP_FREERTOS_STACK
COMPONENT_SRCDIRS += $(AMAZON_FREERTOS_ABSTRACTIONS_DIR)/secure_sockets/freertos_plus_tcp
COMPONENT_OBJEXCLUDE := tcpip_adapter_lwip.o
COMPONENT_PRIV_INCLUDEDIRS := $(AMAZON_FREERTOS_ABSTRACTIONS_DIR)/pkcs11
endif

ifdef CONFIG_TCPIP_LWIP
COMPONENT_SRCDIRS += $(AMAZON_FREERTOS_ABSTRACTIONS_DIR)/secure_sockets/lwip
COMPONENT_OBJEXCLUDE := tcpip_adapter_freertos.o
endif
